version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.0
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_CORS_ORIGINS: "http://localhost:3000"
      KC_HTTP_CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE"
      KC_HTTP_CORS_ALLOW_CREDENTIALS: "true"
      KC_HOSTNAME: "localhost"
    volumes:
      - kc_data:/opt/keycloak/data
      - ./myblockchainapp-realm.json:/opt/keycloak/data/import/myblockchainapp-realm.json
    command:
      - start-dev
      - --features=admin-fine-grained-authz
      - --import-realm

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Blockchain.WebApi/Dockerfile
    ports:
      - "5215:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - keycloak

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      REACT_APP_API_BASE_URL: http://localhost:5215
      REACT_APP_KEYCLOAK_URL: http://localhost:8080
      REACT_APP_KEYCLOAK_REALM: blockchain
      REACT_APP_KEYCLOAK_CLIENT: blockchainapp
    depends_on:
      - backend
      - keycloak

volumes:
  kc_data:
